"""Finds candidate policy statements. Decides nothing."""

from __future__ import annotations

import re
from dataclasses import dataclass

CANDIDATE_FILES = (
    "ai_policy.md",
    "AI_POLICY.md",
    ".github/ai_policy.md",
    "AGENTS.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    ".github/CONTRIBUTING.md",
    "docs/CONTRIBUTING.md",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/pull_request_template.md",
    "PULL_REQUEST_TEMPLATE.md",
    "README.md",
)

QUOTE_MAX_CHARS = 600
QUOTE_MAX_LINES = 8

PATTERNS: dict[str, tuple[str, ...]] = {
    "accepts_external_prs": (
        r"no longer accepting",
        r"not accepting (external|outside|new) ",
        r"pausing external",
        r"do not accept pull requests",
        r"external (pull requests|prs) (are|will be) closed",
        r"closed without review",
        r"we don'?t accept (external|outside)",
    ),
    "requires_issue_first": (
        r"open an issue first",
        r"ask before you start",
        r"before you start",
        r"make sure (that )?there is an issue",
        r"comment on the issue",
        r"claim the issue",
        r"issue (must|should) be (opened|created) (first|before)",
    ),
    "ai_assisted_code": (
        r"\bAI[- ]assisted\b",
        r"\bAI[- ]generated code\b",
        r"\bLLM\b",
        r"\bhuman in the loop\b",
        r"\bautonomous agents?\b",
        r"\b(Claude Code|Copilot|Cursor|Codex|Devin|OpenHands)\b",
        r"\bagent-generated\b",
    ),
    "ai_authored_pr_text": (
        r"AI[- ]generated text",
        r"AI[- ]generated (issue )?descriptions?",
        r"promotional footers",
        r"generated by",
        r"comments that appear to be AI",
        r"don'?t advertise yourself",
    ),
}

COMPILED = {
    claim: [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
    for claim, patterns in PATTERNS.items()
}


@dataclass(frozen=True)
class Candidate:
    claim: str
    source: str
    line_start: int
    line_end: int
    quote: str


def _block_around(lines: list[str], index: int) -> tuple[int, int]:
    start = index
    while start > 0 and lines[start - 1].strip():
        start -= 1
    end = index
    while end < len(lines) - 1 and lines[end + 1].strip():
        end += 1
    if end - start + 1 > QUOTE_MAX_LINES:
        start, end = index, min(index + QUOTE_MAX_LINES - 1, len(lines) - 1)
    return start, end


def scan(files: dict[str, str]) -> list[Candidate]:
    found: list[Candidate] = []
    seen: set[tuple[str, str, int]] = set()

    for path, body in files.items():
        if not body:
            continue
        lines = body.replace("\r\n", "\n").split("\n")
        for index, line in enumerate(lines):
            for claim, patterns in COMPILED.items():
                if not any(pattern.search(line) for pattern in patterns):
                    continue
                start, end = _block_around(lines, index)
                key = (path, claim, start)
                if key in seen:
                    continue
                seen.add(key)
                quote = "\n".join(lines[start : end + 1])[:QUOTE_MAX_CHARS]
                found.append(
                    Candidate(
                        claim=claim,
                        source=path,
                        line_start=start + 1,
                        line_end=end + 1,
                        quote=quote,
                    )
                )
    return found
