"""Finds candidate policy statements. Decides nothing."""

from __future__ import annotations

import re
from dataclasses import dataclass

CANDIDATE_FILES = (
    "ai_policy.md",
    "AI_POLICY.md",
    ".github/ai_policy.md",
    "AGENTS.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    ".github/CONTRIBUTING.md",
    "contributing.md",
    ".github/contributing.md",
    "docs/CONTRIBUTING.md",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/pull_request_template.md",
    "PULL_REQUEST_TEMPLATE.md",
    "README.md",
)

QUOTE_MAX_CHARS = 600
QUOTE_MAX_LINES = 8

PATTERNS: dict[str, tuple[str, ...]] = {
    "accepts_external_prs": (
        r"no longer accepting",
        r"not accepting (external|outside|new) ",
        r"not accepting (external |outside |new )?(pull requests|prs|contributions)",
        r"pausing external",
        r"(do|does|will) not accept (pull requests|prs|contributions)",
        r"not merging (external |outside )?(pull requests|prs)",
        r"external (pull requests|prs) (are|will be) closed",
        r"closed without review",
        r"we don'?t accept (external|outside)",
        r"don'?t accept (external|outside|pull requests|contributions)",
        r"contributions from outside .{0,60}not accepted",
    ),
    "requires_issue_first": (
        r"open an issue first",
        r"ask before you start",
        r"before you start",
        r"make sure (that )?there is an issue",
        r"comment on the issue",
        r"claim the issue",
        r"issue (must|should) be (opened|created) (first|before)",
        r"file an issue before",
        r"discuss (the )?change in an issue before",
        r"(should|must) reference an existing issue",
        r"open an issue before",
        # The verb is not always "open", the noun is not always "issue", and a
        # markdown link routinely splits the two. Each of these is a phrasing
        # that a real project used and that the patterns above walked past.
        r"raise an issue",
        r"open an issue to discuss",
        r"open(ed|ing)? a \[?discussion",
        r"start by \[?opening an issue",
    ),
    "ai_assisted_code": (
        r"\bAI[- ]assisted\b",
        r"\bAI[- ]generated code\b",
        r"\bLLM\b",
        r"\bhuman in the loop\b",
        r"\bautonomous agents?\b",
        r"\b(Claude Code|Copilot|Cursor|Codex|Devin|OpenHands|ChatGPT|Gemini|Aider|Windsurf|Cline|Roo|Continue)\b",
        r"\bagent-generated\b",
        r"\bAI\b",
        r"\bAI tools?\b",
        r"\bAI usage\b",
        r"\buse AI\b",
        r"\bgenerative AI\b",
        r"\bAI polic(y|ies)\b",
        r"\bcoding agents?\b",
        r"\bagentic\b",
    ),
    "ai_authored_pr_text": (
        r"AI[- ]generated text",
        r"AI[- ]generated (issue )?descriptions?",
        r"AI[- ]generated (comments?|replies?|commit messages?)",
        r"promotional footers",
        r"generated by",
        r"comments that appear to be AI",
        r"don'?t advertise yourself",
        r"written by a human",
        r"must be written by you",
        r"do not paste",
    ),
}

COMPILED = {
    claim: [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
    for claim, patterns in PATTERNS.items()
}


@dataclass(frozen=True)
class Candidate:
    claim: str
    source: str
    line_start: int
    line_end: int
    quote: str


def _block_around(lines: list[str], index: int) -> tuple[int, int]:
    start = index
    while start > 0 and lines[start - 1].strip():
        start -= 1
    end = index
    while end < len(lines) - 1 and lines[end + 1].strip():
        end += 1
    if end - start + 1 > QUOTE_MAX_LINES:
        start, end = index, min(index + QUOTE_MAX_LINES - 1, len(lines) - 1)
    return start, end


def scan(files: dict[str, str]) -> list[Candidate]:
    """Scan candidate files for policy-relevant statements and return verbatim quotes.

    ``files`` values are expected to arrive with ``\\n`` line breaks (which
    ``GitHub.raw_file`` already guarantees). Each returned ``Candidate.quote``
    is a literal substring of that normalised text, cropped only by
    ``QUOTE_MAX_CHARS`` -- never stripped, de-indented, or reflowed.
    """
    found: list[Candidate] = []
    seen: set[tuple[str, str, int]] = set()

    for path, body in files.items():
        if not body:
            continue
        lines = body.replace("\r\n", "\n").split("\n")
        for index, line in enumerate(lines):
            for claim, patterns in COMPILED.items():
                if not any(pattern.search(line) for pattern in patterns):
                    continue
                start, end = _block_around(lines, index)
                key = (path, claim, start)
                if key in seen:
                    continue
                seen.add(key)
                quote = "\n".join(lines[start : end + 1])[:QUOTE_MAX_CHARS]
                found.append(
                    Candidate(
                        claim=claim,
                        source=path,
                        line_start=start + 1,
                        line_end=end + 1,
                        quote=quote,
                    )
                )
    return found
